### ISSUE TITLE
License for this project

### ISSUE THREAD

**Issue by LRomano72** [patil215/scrapsort#1]
Hi Neil,

Just reaching out to see what the license T&C's are for this project as I'm looking to create something similar using the Microsoft Azure services for demos and would prefer not to reinvent the wheel if possible. I'm just looking at the software side and not the hardware side of things

Thanks and great work on this,
Leo

**Comment by patil215** [comment]
Hi Leo,

Thanks for bringing this up - the license for the project is GPL-3.0. As long as you keep it open-source, you should be good.

Neil

**Comment by LRomano72** [comment]
Great, thanks Neil!
